is_palindrome function
MIT-Emerging-Talent/ET6-foundations-group-18 pull request #46
Opened 2024-12-31 18:36 UTC by sashour82

coding is_palindrome function and its unit test

---
name: solution review 
about: A template PR for code review with a checklist
---

## Behavior

### Files

- [ ] The file name describes the function's behavior
- [ ] There is a module docstring in the function file
- [ ] The test file's name matches the function file name -
  `/tests/test_file_name.py`
- [ ] There is a module docstring in the tests file

### Unit Tests

- [ ] The test class has a helpful name in PascalCase
- [ ] The test class has a docstring
- Every unit test has
  - [ ] A helpful name
  - [ ] A clear docstring
  - [ ] Only one assertion
  - [ ] There is no logic in the unit test
- [ ] All tests pass
- [ ] There are tests for defensive assertions
- [ ] There are tests for boundary cases

### Function Docstring

- [ ] The function's behavior is described
- The function's arguments are described:
  - [ ] Type
  - [ ] Purpose
  - [ ] Other assumptions (eg. if it's a number, what's the expected range?)
- The return value is described
  - [ ] Type
  - [ ] Other assumptions are documented
- The defensive assertions are documented using `Raises:`
  - [ ] Each assumption about an argument is checked with an assertion
  - [ ] Each assertion checks for _only one_ assumption about the argument
- [ ] Include 3 or more (passing!) doctests

### The Function

- [ ] The function's name describes it's behavior
- [ ] The function's name matches the file name
- [ ] The function has correct type annotations

## Strategy

### Do's

- [ ] Variable names help to understand the strategy
- [ ] Any comments are clear and describe the strategy
- [ ] Lines of code are spaced to help show different stages of the strategy

### Don'ts

- [ ] The function's strategy _is not_ described in the documentation
- [ ] Comments explain the _strategy_, **not** the _implementation_
- [ ] The function _does not_ have more comments than code
  - If it does, consider finding a new strategy or a simpler implementation

## Implementation

- [ ] The code passes the formatting checks
- [ ] The code passes all Ruff linting checks
- [ ] The code has no (reasonable) Pylint errors
  - In code review, you can decide when fixing a Pylint error is helpful and
    when it's too restricting.
- [ ] Variables are named with snake_case
- [ ] Variable names are clear and helpful
- [ ] The code follows the strategy as simply as possible
- [ ] The implementation is as simple as possible given the strategy
- [ ] The code includes defensive assertions
- [ ] Defensive assertions include as little logic as possible

2025-01-05 10:58 UTC, FalaqMajeed commented on solutions/is_palindrome.py
> +Created on XX XX XX
Hey, I noticed the creation date is missing. Could you add the date when this file was created?

2025-01-05 11:03 UTC, FalaqMajeed commented on solutions/tests/test_is_palindrome.py
> +        self.assertTrue(is_palindrome("A man, a plan, a canal, Panama"))
I suggest making one assertion at a time in the tests, each with a clear and helpful name. This will make the tests easier to understand and maintain. Also, it might be helpful to organize the tests into standard cases and edge cases to make them more clear and comprehensive.

2025-01-05 11:10 UTC, FalaqMajeed commented on solutions/tests/test_is_palindrome.py
> +    def test_only_non_alphanumeric(self):
Hey, I recommend changing this test to a more defensive approach. You can write something like:
with self.assertRaises(AssertionError):
    is_palindrome(["!@#$$@!"])
This will help ensure that the function properly handles invalid inputs. Additionally, you could add another defensive test for non-string inputs to make sure the function raises an assertion error for those as well. Just remember to implement these assertions in the function file to make the validation consistent.

2025-01-05 11:14 UTC, FalaqMajeed commented on solutions/is_palindrome.py
> +    # Remove non-alphanumeric characters and convert to lowercase
Hey, I suggest raising an AssertionError for non-string inputs or special characters in the function. This will ensure the function handles defensive cases properly. You can then test these scenarios in the test file, which will help create a clear and strong defensive test. This approach will make the code more robust and prevent unexpected behavior. Example (assert isinstance(s, str), 'Input must be a string')

2025-01-05 11:18 UTC, FalaqMajeed commented on solutions/is_palindrome.py
> +def is_palindrome(s: str) -> bool:
I recommend changing the parameter name from 's' to something more descriptive, like 'input_string' or 'string'. This will improve clarity and make the function easier to understand at a glance. A more specific name helps anyone reading the code quickly grasp its purpose.

2025-01-05 11:22 UTC, FalaqMajeed requested changes
Your function idea is creative and unique! I’ve suggested a few changes to improve clarity. Please address these changes to ensure the code is as clear as possible. Feel free to reach out if anything is unclear or if you need further clarification. Thanks!

2025-01-08 06:45 UTC, sashour82 commented on solutions/is_palindrome.py
> +Created on XX XX XX
done

2025-01-08 06:46 UTC, sashour82 commented on solutions/tests/test_is_palindrome.py
> +        self.assertTrue(is_palindrome("A man, a plan, a canal, Panama"))
done

2025-01-08 06:52 UTC, sashour82 commented on solutions/is_palindrome.py
> +    # Remove non-alphanumeric characters and convert to lowercase
done

2025-01-08 06:53 UTC, sashour82 commented on solutions/is_palindrome.py
> +def is_palindrome(s: str) -> bool:
done

2025-01-08 10:36 UTC, FalaqMajeed approved these changes
Thank you for considering my suggestion and updating the code! The changes look fantastic and align perfectly with the checklist requirements.

2025-01-08 10:36 UTC, merged